chestxdet10_gt:
  name: "chestxdet10_gt"
  data_type: "image_classification"
  data_path: "/cluster/projects/mcintoshgroup/CXR-CLIP/preprossed_dataset_csv/chestXDet10/test.csv"
  n_class: 10
  normalize: ${designs.model.image_encoder.configs.normalize}