mimic_cxr:
  name: "mimic_cxr"
  data_type: "imagetext_eval"
  # data_path: "/cluster/projects/mcintoshgroup/CXR-CLIP/mimic_cxr_jpg_metadata/mimic_test_png.csv"
  data_path: "/cluster/projects/mcintoshgroup/CXR-CLIP/preprossed_dataset_csv/mimic-cxr/mimic_test_png_multihot204.csv" # the latest version checked on 25/09/2025
  normalize: ${designs.model.image_encoder.configs.normalize}
