base:
  name: "physician_padchest207"
  data_type: "image_classification"
  data_path: "/cluster/projects/mcintoshgroup/CXR-CLIP/preprossed_dataset_csv/padchest/padchest_test_for_fs.csv"
  # data_path: "/cluster/projects/mcintoshgroup/CXR-CLIP/preprossed_dataset_csv/padchest/padchest_val_for_fs.csv"
  n_class: 187 # instead of 204 based on preprocess_padchest, only relevant in the few-shot finetuning.
  image_size: ${base.image_size}
  enable_dqn_fewshot: ${oc.select:designs.enable_dqn_fewshot,false}
  for_fintuning: true
