base:
  name: "chestxdet10"
  data_type: "image_classification"
  data_path: "/cluster/projects/mcintoshgroup/CXR-CLIP/preprossed_dataset_csv/chestXDet10/chestXDet10_train_for_fs.csv"
  image_size: ${base.image_size}
  n_class: 10
  # fine tune params
  data_frac: ${oc.select:base.data_frac,1.0}
  sample_shots_not_percentage: ${oc.select:base.sample_shots_not_percentage,false}
  enable_dqn_fewshot: ${oc.select:designs.enable_dqn_fewshot,false}
  for_fintuning: true
