mimic_cxr:
  name: "mimic_cxr"
  data_type: "imagetext"
  data_path: "PATH TO DATA CSV FILE." # the latest version checked on 25/09/2025
  image_size: ${base.image_size}
  text_max_length: ${base.text_max_length}
  prompt_max_length: ${base.prompt_max_length}
  dqn_label_max_length: ${base.dqn_label_max_length}
  data_frac: 1.0
  labels_sample_size: ${designs.data.labels_sample_size}
  add_alignment_prompt_prefix: ${designs.data.add_alignment_prompt_prefix}
  report_col: ${designs.data.report_col} # default is "text"
  augmented_report_col: ${designs.data.augmented_report_col}  # default is "text_augment" only matters on with augmention_type == 'cxrclip'
  augmentation_type: ${designs.data.augmentation_type}
  alignment_prompt_col: ${designs.data.alignment_prompt_col}
  normalize: ${designs.model.image_encoder.configs.normalize}
  observation_explanation: ${designs.data.observation_explanation}
  anonymize_observation_explanation: ${designs.data.anonymize_observation_explanation}
  use_random_description: ${designs.data.use_random_description}
  random_description_prob: ${designs.data.random_description_prob}
  enable_positive_negative_label_swapping: ${designs.data.enable_positive_negative_label_swapping}

  positive_label_col: positives_label_withLocation
  negative_label_col: negatives_label_withLocation
  positive_prompt_col: positive_withLocation_prompts_qwen30b
  negative_prompt_col: negative_withLocation_prompts_qwen30b
  # THIS CONFIG IS CXRCLIP STYLE TRAINNIG BUT WITH CLEANED REPORT USING QWEN INSTEAD.