source: "stanford_aiml" 
name: 'xraydinov2_224'
pretrained: ${designs.model.image_encoder.pretrained}
model_type: 'ViT'
cache_dir: '/cluster/projects/mcintoshgroup/CXR-CLIP/xraydinov2_224'
dual_cls: ${designs.model.image_encoder.vision_dual_cls}
normalize: 'dinov2'
freeze_backbone: ${designs.model.image_encoder.freeze_backbone}
