train:
  pin_memory: True
  shuffle: True
  drop_last: True
  num_workers: 1
  prefetch_factor: 8
  batch_size: 64

valid:
  pin_memory: True
  shuffle: False
  drop_last: False
  num_workers: 10
  prefetch_factor: 8
  batch_size: 256

test:
  pin_memory: True
  shuffle: False
  drop_last: False
  num_workers: 10
  batch_size: 256
