CHEST14 = [
    "Atelectasis",
    "Cardiomegaly",
    "Consolidation",
    "Edema",
    "Effusion",
    "Emphysema",
    "Fibrosis",
    "Hernia",
    "Infiltration",
    "Mass",
    "Nodule",
    "Pleural Thickening", # Pleural_Thickening
    "Pneumonia",
    "Pneumothorax",
    # "No Finding" # other baseline does not include this.
]

CHESTXDET10 = [
    'Atelectasis',
    'Calcification',
    'Consolidation',
    'Effusion',
    'Emphysema',
    'Fibrosis',
    'Fracture',
    'Mass',
    'Nodule',
    'Pneumothorax'
]

CHESTXDET10_GT = [
    'Atelectasis',
    'Calcification',
    'Consolidation',
    'Effusion',
    'Emphysema',
    'Fibrosis',
    'Fracture',
    'Mass',
    'Nodule',
    'Pneumothorax'
]

CHEXPERT = ["Atelectasis", "Cardiomegaly", "Consolidation", "Edema", "Pleural Effusion"]

PHYSICIAN_PADCHEST207 = [
    'abnormal foreign body', 
    'abscess', 
    'adenopathy', 
    'air bronchogram', 
    'air fluid level', 
    'air trapping', 
    'alveolar pattern', 
    'aortic aneurysm', 
    'aortic atheromatosis', 
    'aortic button enlargement', 
    'aortic elongation', 
    'aortic endoprosthesis', 
    # 'aortic enlargement', 
    'apical pleural thickening', 
    'artificial aortic heart valve', 
    'artificial heart valve', 
    'artificial mitral heart valve', 
    'asbestosis signs', 
    'ascendent aortic elongation', 
    'atelectasis', 
    'atelectasis basal', 
    'atypical pneumonia', 
    'axial hyperostosis', 
    'azygoesophageal recess shift', 
    'azygos lobe', 
    'blastic bone lesion', 
    'bone cement', 
    'bone metastasis', 
    'breast mass', 
    'bronchiectasis', 
    'bronchovascular markings', 
    'bullas', 
    # 'calcification', 
    'calcified adenopathy', 
    'calcified densities', 
    'calcified fibroadenoma', 
    'calcified granuloma', 
    'calcified mediastinal adenopathy', 
    'calcified pleural plaques', 
    'calcified pleural thickening', 
    'callus rib fracture', 
    'cardiomegaly', 
    'catheter', 
    'cavitation', 
    'central vascular redistribution', 
    'central venous catheter', 
    'central venous catheter via jugular vein', 
    'central venous catheter via subclavian vein', 
    'central venous catheter via umbilical vein', 
    'cervical rib', 
    'chest drain tube', 
    'chilaiditi sign', 
    # 'chronic obstructive pulmonary disease', # TODO: newly modified
    'clavicle fracture', 
    'consolidation', 
    'copd', 
    'costochondral junction hypertrophy', 
    'costophrenic angle blunting', 
    'cyst', 'descendent aortic elongation', 
    'dextrocardia', 
    'diaphragmatic eventration', 
    'double j stent', 
    'dual chamber device', 
    'edema', 
    'effusion', 
    'electrical device', 
    'emphysema', 
    'empyema', 
    'endoprosthesis', 
    'endotracheal tube', 
    # 'enlarged cardiomediastinum', 
    # 'enlarged pulmonary artery', 
    'esophagic dilatation', 
    'fibrosis', 
    'fibrotic band', 
    'fissure thickening', 
    'flattened diaphragm', 
    'fracture', 
    'gastrostomy tube', 
    'goiter', 
    'granuloma', 
    'ground glass pattern', 
    'gynecomastia', 
    'heart insufficiency', 
    'heart valve calcified', 
    'hemidiaphragm elevation', 
    'hernia', 
    'hiatal hernia', 
    'hilar congestion', 
    'hilar enlargement', 
    'humeral fracture', 
    'humeral prosthesis', 
    'hydropneumothorax', 
    'hyperinflated lung', 
    'hypoexpansion', 
    'hypoexpansion basal', 
    'increased density', 
    'infiltrates', 
    # 'infiltration', 
    # 'interlobular septal thickening', 
    # 'interstitial lung disease', 
    'interstitial pattern', 
    'kerley lines', 
    'kyphosis', 
    'laminar atelectasis', 
    'lepidic adenocarcinoma', 
    'lipomatosis', 
    'lobar atelectasis', 
    'loculated fissural effusion', 
    'loculated pleural effusion', 
    # 'lung cavity', 
    # 'lung cyst', 
    'lung metastasis', 
    # 'lung opacity', 
    # 'lung tumor', 
    'lung vascular paucity', 
    # 'lymphadenopathy', 
    'lymphangitis carcinomatosa', 
    'lytic bone lesion', 
    'major fissure thickening', 
    'mammary prosthesis', 
    'mass', 
    'mastectomy', 
    'mediastinal enlargement', 
    'mediastinal mass', 
    'mediastinal shift', 
    'mediastinic lipomatosis', 
    'metal', 
    'miliary opacities', 
    'minor fissure thickening', 
    'multiple nodules', 
    'nephrostomy tube', 
    'nipple shadow', 
    # 'no findings', 
    'nodule', 
    'non axial articular degenerative changes', 
    'nsg tube', 
    'obesity', 
    'osteopenia', 
    'osteoporosis', 
    'osteosynthesis material', 
    'pacemaker', 
    'pectum carinatum', 
    'pectum excavatum', 
    # 'peribronchial thickening', 
    'pericardial effusion', 
    'pleural effusion', 'pleural mass', 'pleural plaques', 'pleural thickening', 'pneumomediastinum', 'pneumonia', 'pneumoperitoneo', 'pneumothorax', 'prosthesis', 'pulmonary artery enlargement', 'pulmonary artery hypertension', 'pulmonary edema', 'pulmonary fibrosis', 
    # 'pulmonary fibrotic sequela', 
    'pulmonary hypertension', 'pulmonary mass', 'pulmonary venous hypertension', 'reservoir central venous catheter', 
    # 'respiratory distress', 
    'reticular interstitial pattern', 'reticulonodular interstitial pattern', 'rib fracture', 'right sided aortic arch', 'round atelectasis', 'sclerotic bone lesion', 'scoliosis', 'segmental atelectasis', 'single chamber device', 'soft tissue mass', 'sternoclavicular junction hypertrophy', 'sternotomy', 'subacromial space narrowing', 'subcutaneous emphysema', 'suboptimal study', 'superior mediastinal enlargement', 'supra aortic elongation', 'surgery', 'surgery breast', 'surgery heart', 'surgery humeral', 'surgery lung', 'surgery neck', 'suture material', 'thoracic cage deformation', 'total atelectasis', 'tracheal shift', 'tracheostomy tube', 'tuberculosis', 'tuberculosis sequelae', 'vascular hilar enlargement', 'vascular redistribution', 'ventriculoperitoneal drain tube', 'vertebral anterior compression', 'vertebral compression', 'vertebral degenerative changes', 'vertebral fracture', 'volume loss']


if __name__ == '__main__':
    pass