source: "laihaoran" # one of { "huggingface"}
name: Laihaoran/BioClinicalMPBERT
pretrained: ${designs.model.text_encoder.pretrained}
gradient_checkpointing: false
pooling: ${designs.model.text_encoder.pooling}  # one of { "eos" | "bos" | "mean" } # TODO: check text_model.py in the CARZero repo for token used for sentence embedding.
cache_dir: '/cluster/projects/mcintoshgroup/CXR-CLIP/CARZero/Laihaoran_BioClinicalMPBERT'
carzero_pretrained_dir: '/cluster/projects/mcintoshgroup/CXR-CLIP/CARZero/pretraining_weights/carzero_best_txt_encoder.ckpt'
trust_remote_code: true
mlm_head: true
dual_cls: ${designs.tokenizer.text_dual_cls}