source: "laihaoran" # one of { "huggingface"}
name: Laihaoran/BioClinicalMPBERT
pretrained: ${oc.select:designs.model.text_encoder.pretrained,true}
gradient_checkpointing: false
pooling: ${oc.select:designs.model.text_encoder.pooling,'bos'} # one of { "eos" | "bos" | "mean" } # NOTE: should be correct. check text_model.py in the CARZero repo for token used for sentence embedding.
cache_dir: '/cluster/projects/mcintoshgroup/CXR-CLIP/CARZero/Laihaoran_BioClinicalMPBERT'
trust_remote_code: true
mlm_head: true
dual_cls: ${oc.select:designs.tokenizer.text_dual_cls,false}

# independently SSL trained Bert model